### ISSUE TITLE
Function in polyfills/all.js leads to jump to chart embed position in Android WebView

### ISSUE THREAD

**Issue by peyerc** [datawrapper/polyfills#13]
We've located a function call in "polyfills/all.js" which causes a jump in our Android App WebView to the chart embed position.

https://github.com/datawrapper/polyfills/blob/4115efed35f82848da294ed1281e6189300fe0d3/polyfills/all.js#L87

The exact call is "e.appendChild(t).focus()", that causes the problem.

To replicate the behavior you can create a simple WebView which loads a Webpage, which has a chart embed at a location not visible in the view port. When the page is fully loaded, the WebView jumps and chart is at the top position.

```
package ch.srf.webviewtest

import android.os.Bundle
import android.webkit.WebView
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val webView = WebView(applicationContext)

        webView.getSettings().setJavaScriptEnabled(true)

        setContentView(webView)
        webView.loadUrl("http://127.0.0.1:8000/webview_map_test.html")
    }

}

```

The chart we are using in the web page is: https://datawrapper.dwcdn.net/5qEnO/1/

**Comment by ilokhov** [comment]
Thanks for opening the issue.

We're aware of this behaviour and implemented a fix for it here: https://github.com/datawrapper/polyfills/pull/12

The fix resolves the problem by ensuring that `all.js` does not get loaded in the Android App WebView - it worked for us when testing on Android devices.

You may need to re-publish your map(s)/charts in order to apply the fix in them.

Let me know if the fix does not work for you.

**Comment by peyerc** [comment]
Thank you for the quick response. A re-publish of the map fixed the issue we had in our WebView.
